version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=filmdump
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./MS_API_V0.1
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - mongo
 
volumes:
  mongo_data:
    driver: local

    

