version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=filmdump
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./MS_API_V0.1
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - mongo

  web:
    build:
      context: ./MS_FE_V0.1
      dockerfile: Dockerfile
    volumes:
      - ./MS_FE_V0.1:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    
 
volumes:
  mongo_data:
    driver: local
  node_modules: 

    

